image: ruby:2.7.0
stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy:
  environment: production
  stage: deploy
  script:
    - gem install capistrano -v 3.13.0
    - gem install capistrano-rails -v 1.4.0
    - gem install capistrano3-unicorn -v 0.2.1
    - gem install capistrano-rvm -v 0.1.2
    - cap production deploy
  only:
    - develop