image: ruby:2.7.1
stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy:
  environment: production
  stage: deploy
  script:
    - gem install capistrano -v 3.14.1
    - gem install capistrano-rails
    - gem install capistrano3-unicorn
    - gem install capistrano-rbenv
    - cap production deploy
  only:
    - develop