version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "foreman start -f Procfile.prod-server"
    volumes:
      - '.:/app'
    expose:
      - "80"
    ports:
      - '80:80'
    networks:
      - postgres
    links:
      - db
    depends_on:
      - db
networks:
  postgres:
    driver: bridge