default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: cert_development
  username: postgres
  password: root
  host: localhost

test:
  <<: *default
  database: cert_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>