default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: cert_development
  username: postgres
  password: root
  host: localhost

test:
  <<: *default
  database: cert_test

production:
  <<: *default
  database: cert_production
  host: db
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>