default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: cert_development
  username: postgres
  password: root
  host: localhost

test:
  <<: *default
  database: cert_test

production:
  <<: *default
  host: danielarrais.dev
  database: cert_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>